<?php
// config/<USER_NAME>/config.api.php
// This config/<USER_NAME>/config.api.php file is automatically generated by setup_auth.php
// EXPECTED_TOKEN : Standard API token (read / append / normal access)
// ADMIN_TOKEN    : Strong token for cleanup (destructive operations)
// DATA_JSON      : Absolute path to data.json used by the API
return [
    'EXPECTED_TOKEN' => 'CHANGE_ME_EXPECTED_TOKEN',
    'ADMIN_TOKEN'    => 'CHANGE_ME_ADMIN_TOKEN',

    // Absolute path to data.json as seen from api.php / read_api.php / cleanup_api.php
    // In the multi-user version, it points to notemod-data/<USER_NAME>/data.json
    'DATA_JSON'      => dirname(__DIR__, 2) . '/notemod-data/' . '<USER_NAME>' . '/data.json',

    // Default color for newly created categories/notes
    // (Hex-like string following Notemod's internal format)
    'DEFAULT_COLOR'  => '3478bd',

    // Whether to create a backup before cleanup
    // true  : Create a backup of data.json before cleanup
    // false : Do not create a backup
    'CLEANUP_BACKUP_ENABLED' => true,

    // Backup filename suffix
    // Example: data.json.bak-YYYYMMDD-HHMMSS
    // Normally, do not change this for compatibility
    'CLEANUP_BACKUP_SUFFIX'  => '.bak-',

    // Maximum number of backups to keep (oldest ones are removed first)
    'CLEANUP_BACKUP_KEEP'    => 10,
];
