<?php
// config/config.php
// This config/config.php file was automatically generated by setup_auth.php
return [
    // PHP timezone setting (examples)
    // Japan : Asia/Tokyo
    // NZ    : Pacific/Auckland
    // AU    : Australia/Sydney
    // US    : America/Los_Angeles / America/New_York
    // Canada: America/Toronto / America/Vancouver
    // Turkey: Europe/Istanbul
    'TIMEZONE' => 'Asia/Tokyo',

    // Set to true to enable debug logging
    'DEBUG' => false,

    // Enable/disable logger
    // Raw access logs (/logs/access-YYYY-MM.log)
    'LOGGER_FILE_ENABLED' => true,

    // Record to Notemod Logs category (monthly note: access-YYYY-MM)
    'LOGGER_NOTEMOD_ENABLED' => false,

    // Enable/disable automatic backup before Web UI sync save
    'SYNC_PRE_SAVE_BACKUP_ENABLED' => true,

    // Automatically prune old backups immediately before Web UI sync pre-save backup
    'SYNC_PRE_SAVE_BACKUP_PRUNE_ENABLED' => false,

    // Enable/disable data encryption
    'DATA_ENCRYPTION_ENABLED' => false,

    // Data encryption key
    // In production, set a sufficiently long random string
    'DATA_ENCRYPTION_KEY' => 'CHANGE_ME_DATA_ENCRYPTION_KEY',

    // Session cookie lifetime
    // 0 = Until browser is closed
    // 86400 = 1 day
    // 604800 = 7 days
    // 2592000 = 30 days
    'SESSION_COOKIE_LIFETIME' => 0,

    // Optional: customize Notemod initial snapshot
    // (Must be stored as a JSON string)
    // 'INITIAL_SNAPSHOT' => '{"categories":null,"hasSelectedLanguage":null,"notes":null,"selectedLanguage":null}',

    // Initial IP Access Notification (Email)
    'IP_ALERT_ENABLED' => false,                    // Enable: true
    'IP_ALERT_TO'      => 'YOUR_EMAIL',            // Send to:
    'IP_ALERT_FROM'    => 'no-reply@notemod',      // From: optional
    'IP_ALERT_SUBJECT' => 'Notemod: First-time IP access', // Email subject
    'IP_ALERT_IGNORE_BOTS' => true,                // Ignore user agents that are likely bots
    'IP_ALERT_IGNORE_IPS' => array(),              // Exclude your own fixed IP addresses, etc.
    // IP_ALERT_STORE is usually unnecessary
    // When unset, logger.php automatically uses notemod-data/<DIR_USER>/_known_ips.json

    // 0 = No limit (do nothing)
    // Example: Monthly raw logs (access-YYYY-MM.log) — up to 500 lines
    //          Notemod Logs — notes limited to 50 lines
    'LOGGER_FILE_MAX_LINES' => 500,
    'LOGGER_NOTEMOD_MAX_LINES' => 50,

    // Application secret used as a private value
    // (signing, encryption, fixed keys, etc.)
    // If not specified, setup_auth.php will append it automatically
    'SECRET' => 'CHANGE_ME_SECRET',
];
