<?php
// config/config.api.php
// This config/config.api.php file was automatically generated by setup_auth.php
// EXPECTED_TOKEN : Token for normal API access (add/read notes, etc.)
// ADMIN_TOKEN    : Strong token for cleanup (destructive operations)
// DATA_JSON      : Absolute path to data.json
return [
    'EXPECTED_TOKEN' => 'CHANGE_ME_EXPECTED_TOKEN',
    'ADMIN_TOKEN' => 'CHANGE_ME_ADMIN_TOKEN',

    // Absolute path to data.json as seen from api.php / read_api.php / cleanup_api.php
    // This sample assumes config/<USER_NAME>/config.api.php
    // and notemod-data/<USER_NAME>/data.json
    'DATA_JSON'      => dirname(__DIR__, 2) . '/notemod-data/' . 'YOUR_DIR_USER' . '/data.json',

    // Default color for newly created categories/notes
    // (Hex-like string, following Notemod’s internal format)
    'DEFAULT_COLOR'  => '3478bd',

    // Whether to create a backup when running cleanup
    // true  : Save data.json as .bak-YYYYmmdd-HHiiSS before execution
    // false : Do not create a backup
    'CLEANUP_BACKUP_ENABLED' => true,

    // (Optional) Backup filename suffix
    // Example: use 'data.json.bak-' if you want that format
    // Do NOT change this if you want ClipboardSender
    // to bulk-delete backup files
    'CLEANUP_BACKUP_SUFFIX' => '.bak-',

    // Maximum number of backup files to keep
    'CLEANUP_BACKUP_KEEP' => 10,
];
