<?php
// config/<USER_NAME>/config.php
// This config/<USER_NAME>/config.php file is automatically generated by setup_auth.php
return [
    // PHP timezone setting (examples)
    // Japan : Asia/Tokyo
    // NZ    : Pacific/Auckland
    // AU    : Australia/Sydney
    // US    : America/Los_Angeles / America/New_York
    // Canada: America/Toronto / America/Vancouver
    // Turkey: Europe/Istanbul
    'TIMEZONE' => 'Asia/Tokyo',

    // Set to true to enable debug logging
    'DEBUG' => false,

    // Enable / disable logger
    // Raw access logs (logs/<USER_NAME>/access-YYYY-MM.log)
    'LOGGER_FILE_ENABLED' => true,

    // Write to the Notemod Logs category (monthly note: access-YYYY-MM)
    'LOGGER_NOTEMOD_ENABLED' => false,

    // Create an automatic backup before Web UI sync save
    'SYNC_PRE_SAVE_BACKUP_ENABLED' => true,

    // Automatically prune old backups immediately before the sync pre-save backup
    'SYNC_PRE_SAVE_BACKUP_PRUNE_ENABLED' => false,

    // data.json encryption settings
    // The encryption key is automatically generated by setup_auth.php
    'DATA_ENCRYPTION_ENABLED' => false,
    'DATA_ENCRYPTION_KEY' => 'CHANGE_ME_DATA_ENCRYPTION_KEY',

    // Session cookie lifetime
    // 0 = until the browser is closed
    // 86400 = 1 day / 604800 = 7 days / 2592000 = 30 days
    'SESSION_COOKIE_LIFETIME' => 0,

    // First-time IP access alert (email)
    'IP_ALERT_ENABLED' => false,
    'IP_ALERT_TO' => 'YOUR_EMAIL',
    'IP_ALERT_FROM' => 'no-reply@notemod',
    'IP_ALERT_SUBJECT' => 'Notemod: First-time IP access',
    'IP_ALERT_IGNORE_BOTS' => true,
    'IP_ALERT_IGNORE_IPS' => array(),
    // IP_ALERT_STORE is normally unnecessary
    // logger.php automatically uses notemod-data/<USER_NAME>/_known_ips.json

    // Logger line limits
    // 0 = no limit
    'LOGGER_FILE_MAX_LINES' => 500,
    'LOGGER_NOTEMOD_MAX_LINES' => 50,

    // Application secret used internally
    // Used for signing, encryption, fixed keys, etc.
    // If omitted, setup_auth.php generates it automatically
    'SECRET' => 'CHANGE_ME_SECRET',
];
