<?php
// config/config.php
// This config/config.php file was automatically generated by setup_auth.php
return [
    // PHP timezone setting (examples)
    // Japan : Asia/Tokyo
    // NZ    : Pacific/Auckland
    // AU    : Australia/Sydney
    // US    : America/Los_Angeles / America/New_York
    // Canada: America/Toronto / America/Vancouver
    // Turkey: Europe/Istanbul
    'TIMEZONE' => 'Asia/Tokyo',

    // Set to true to enable debug logging
    'DEBUG' => false,

    // Enable/disable logger
    // Raw access logs (/logs/access-YYYY-MM.log)
    'LOGGER_FILE_ENABLED' => true,

    // Notemod Logs category (monthly note: access-YYYY-MM)
    'LOGGER_NOTEMOD_ENABLED' => true,

    // (Optional) Change the logs directory name
    // 'LOGGER_LOGS_DIRNAME' => 'logs',

    // Optional: customize Notemod initial snapshot
    // (Must be stored as a JSON string)
    // 'INITIAL_SNAPSHOT' => '{"categories":null,"hasSelectedLanguage":null,"notes":null,"selectedLanguage":null}',

    // Initial IP Access Notification (Email)
    'IP_ALERT_ENABLED' => true,                      // Enable: true
    'IP_ALERT_TO'      => 'YOUR_EMAIL', // Send To:
    'IP_ALERT_FROM' => 'notemod@localhost',    // Recipient: Optional (if configurable)
    'IP_ALERT_SUBJECT' => 'Notemod: First-time IP access', // Email subject
    'IP_ALERT_IGNORE_BOTS' => true,                  // Ignore user agents that are likely bots
    'IP_ALERT_IGNORE_IPS' => [''],                   // Exclude your own fixed IP addresses, etc.
    // 'IP_ALERT_STORE' => __DIR__ . '/../notemod-data/_known_ips.json', // Optional

    // 0 = No limit (do nothing)
    // Example: Monthly raw logs (access-YYYY-MM.log) — up to 2,000 lines
    // Notemod Logs — Notes limited to 50 lines
    'LOGGER_FILE_MAX_LINES' => 500,
    'LOGGER_NOTEMOD_MAX_LINES' => 50,

    // Application secret used as a private value
    // (signing, encryption, fixed keys, etc.)
    // If not specified, setup_auth.php will append it automatically
    'SECRET' => 'CHANGE_ME_SECRET',
];